### ISSUE TITLE
kmod-wireguard: cannot find dependency kmod-crypto-kpp for kmod-crypto-lib-curve25519

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/openwrt#16169]
### Describe the bug

ubuntu 22.04LTS
openwrt master latest
mediatek/filogic 
bananapi_bpi-r3-mini
kmod-wireguard
```
CCollected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-crypto-kpp for kmod-crypto-lib-curve25519
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-lib-curve25519 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-crypto-lib-curve25519.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-wireguard:
 *      kmod-crypto-kpp
 * opkg_install_cmd: Cannot install package kmod-wireguard.
 ```

### OpenWrt version

SNAPSHOT

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic 

### Device

bananapi_bpi-r3-mini

### Image kind

Self-built image

**Comment by peterwillcn** [comment]
> Invalid Release reported. `master` Is this from a clean repository?

SNAPSHOT

**Comment by peterwillcn** [comment]
add fixed
```
CONFIG_KERNEL_BIG_KEYS=y
CONFIG_KERNEL_KEYS_REQUEST_CACHE=y
CONFIG_KERNEL_PERSISTENT_KEYRINGS=y
```

**Comment by Neustradamus** [comment]
@peterwillcn: It has been fixed upstream?

**Comment by peterwillcn** [comment]
> @peterwillcn: It has been fixed upstream?

Upstream configuration seed has not been fixed yet.

**Comment by nroach44** [comment]
Can confirm that the three config changes are still required for the build to complete on 2023.05.05.

**Comment by valkodev** [comment]
For me this didn't helped. Still getting the error during packgage installation. Treid snapshot as well as latest new tag 24.10. Without Wireguard the compliation is working fine. Tried to do distclean, same result. Any idea what to try? Thanks in advance.

Target architecture is ATH79

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-crypto-kpp for kmod-crypto-lib-curve25519
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-lib-curve25519 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-crypto-lib-curve25519.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-wireguard:
 * 	kmod-crypto-kpp
 * opkg_install_cmd: Cannot install package kmod-wireguard.

**Comment by mantheman** [comment]
> For me this didn't helped. Still getting the error during packgage installation. Treid snapshot as well as latest new tag 24.10. Without Wireguard the compliation is working fine. Tried to do distclean, same result. The solutiuon was to select kmod-crypto-kpp wit * instead of M. No need to change above 3 KERNEL config values.
> 
Just upgraded from 24.10.4 to today's master. Can confirm I had to manually enable kmod-crypto-kpp or kmod-crypto-lib-curve25519 would throw an error. In menunconfig for kmod-crypto-kpp it says:

Implied by [y]:                                                                                                                                                                                                                      x
  x   - PACKAGE_kmod-crypto-lib-curve25519 [=y]

I don't know exactly "implied" means. (apart from the obvious) Maybe it should be a dependency instead?
