### ISSUE TITLE
realtek: SFPs on GS1900-48 and 1920-48G

### ISSUE THREAD

**Issue by jwh** [openwrt/openwrt#18665]
### Describe the bug

Just curious if anyone is working on this more than anything, I've got test hardware if required and actually have some time to test if someone is working on this and wants some testing?

GS1900-48 is still the same, although ethtool -m shows light etc, the link doesn't come up unless `rtk network on` is issued before booting.

1920-48G is still completely unsupported according to the DTS, did the work to get the RTL8214FC working ever get merged?

### OpenWrt version

master

### OpenWrt release

master

### OpenWrt target/subtarget

realtek/rtl839x

### Device

GS1900-48 and 1920-48G

### Image kind

Self-built image

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by plappermaul** [comment]
If DTS is right HPE 1920-48G has RTL8214FC while Zyxel GS1900-48 has direct SFP connections. What does bus detection output during startup say?

**Comment by jwh** [comment]
I've put the entire dmesg here as I don't know what you want specifically: https://0x0.st/84Pq.txt (after sysupgrade)

I'm running HEAD + a couple of your PRs that are merged into my tree but it doesn't change the behaviour so shouldn't matter

**Comment by jwh** [comment]
Also for completeness, dmesg and ethtool output from GS1900-48: https://0x0.st/84PM.txt

**Comment by plappermaul** [comment]
Don't want to disappoint you but to get this stuff working a lot needs to be done.

- The SerDes that connects the SoC to the peripherals needs to be patched properly. Maybe some day we get https://lists.infradead.org/pipermail/linux-phy/2025-April/021621.html)
- In case we have a PHY (like the RTL8214FC) this needs to be patched too.
- In case we have a direct connection we might need to to some SerDes calibration

As I'm working a little bit on RTL8214FC (https://github.com/openwrt/openwrt/issues/16438) we can give the HP a try. My assumption is that you have the following situation:

- The TP port does not react at all
- Inserting/removing SFP modules does not handle anything (no "POWER UP/DOWN FIBER/COPPER" messages on console)

For the second issue please try this patch:

```
static int rtl8214fc_phy_probe(struct phy_device *phydev)
{
	struct device *dev = &phydev->mdio.dev;
	int addr = phydev->mdio.addr;
	int ret = 0;

	/* 839x has internal SerDes */
	if (soc_info.id == 0x8393) <<< WRONG, REMOVE
		return -ENODEV; <<< WRONG, REMOVE

	/* All base addresses of the PHYs start at multiples of 8 */
	devm_phy_package_join(dev, phydev, addr & (~7),
				sizeof(struct rtl83xx_shared_private));

	if (!(addr % 8)) {
		struct rtl83xx_shared_private *shared = phydev->shared->priv;
		shared->name = "RTL8214FC";
		/* Configuration must be done while patching still possible */
		if (soc_info.family == RTL8380_FAMILY_ID) <<< AVOID PATCHING ON 839X, ADD
			ret = rtl8380_configure_rtl8214fc(phydev); <<< AVOID PATCHING ON 839X, ADD
		if (ret)
			return ret;
	}

	return phy_sfp_probe(phydev, &rtl8214fc_sfp_ops);
}

```
With this I expect:

- Message " rtl83xx-switch switch@1b000000 lan50 (uninitialized): PHY [mdio-bus:30] driver [Generic PHY] (irq=POLL)" changes to "rtl83xx-switch switch@1b000000 lan50 (uninitialized): PHY [mdio-bus:30] driver [RTL8214FC] (irq=POLL)"
- Inserting/removing the SFP modules gives UP/DOWN messages

**Comment by jwh** [comment]
Yeah I expected it would be a lot of work, but if I can help I will (can give ssh with serial to all the switches I have here etc, they're wired up in my lab):

[   14.168777] rtl8214fc_power_set: Powering off FIBRE (port 48)
[   14.189277] rtl8214fc_power_set: Powering on COPPER (port 48)
[   14.210942] rtl83xx-switch switch@1b000000 lan50 (uninitialized): PHY [mdio-bus:30] driver [Realtek RTL8214FC] (irq=POLL)
[   14.251960] rtl8214fc_power_set: Powering off FIBRE (port 49)
[   14.272429] rtl8214fc_power_set: Powering on COPPER (port 49)
[   14.294071] rtl83xx-switch switch@1b000000 lan52 (uninitialized): PHY [mdio-bus:31] driver [Realtek RTL8214FC] (irq=POLL)
[   14.334791] rtl8214fc_power_set: Powering off FIBRE (port 50)
[   14.355157] rtl8214fc_power_set: Powering on COPPER (port 50)
[   14.376771] rtl83xx-switch switch@1b000000 lan49 (uninitialized): PHY [mdio-bus:32] driver [Realtek RTL8214FC] (irq=POLL)
[   14.417487] rtl8214fc_power_set: Powering off FIBRE (port 51)
[   14.437892] rtl8214fc_power_set: Powering on COPPER (port 51)
[   14.459541] rtl83xx-switch switch@1b000000 lan51 (uninitialized): PHY [mdio-bus:33] driver [Realtek RTL8214FC] (irq=POLL)

I don't see any insert/remove messages though and ethtool -m still returns no such device

Do you know what needs to be done for the GS1900-48? Is it dependent on that patch? I can merge that locally if it would help.  Insert/remove and SFP EEPROM etc all works there, it just never brings the link up, presumably `rtk network on` does some setup that needs to be replicated in the driver?

**Comment by plappermaul** [comment]
Will send a patch for that little issue.

So SFP handlers are initialized properly. Now to the next thing. They should get triggered if you insert/remove SFP modules and should at least give messages like that:

```
sfp sfp-3: module UBNT             UF-MM-1G         rev      sn FT17110800935    dc 171108
rtl8214fc_media_set: port 27, set_fibre: 1
rtl8214fc_power_set: Powering off COPPER (port 27)
rtl8214fc_power_set: Powering on FIBRE (port 27)

```

If this does not happen then you have issues with your I2C and GPIO settings in the DTS. Especially 

- "mod-def0-gpio = ..." must be set properly otherwise insertion removal is not detected
- "sda-gpio = ..." and "scl-gpio = ..." must be set properly so that Linux can determine the properties of the module

If mod-def0 is wrong you do not see anything. If it is set ok and sda/scl is wrong you see "module slow respond".

**Comment by plappermaul** [comment]
IIRC the HP has a UBoot feature that tells you the proper GPIOs so you can avoid manual measuring the connections on the board.

https://forum.openwrt.org/t/support-for-rtl838x-based-managed-switches/57875/105?u=plappermaul

**Comment by plappermaul** [comment]
> On the 1920?

Fo now we focus on the HP with the RTL8214FC.

**Comment by jwh** [comment]
Also actually, I don't think the HP has that, the D-link definitely does, HP has bootware which I don't think exposes a u-boot interface (even if it is u-boot underneath), but it probably shows it in stock OS - I'll have to wait until the next 48G arrives to check that unless I can probe it from openwrt somehow

**Comment by plappermaul** [comment]
Uboot maybe wrong from me. But the forum post states: "The OEM firmware has that show tech-support command built in"

**Comment by jwh** [comment]
Yeah, I remember that - will need to wait until the other 48Gs arrive unless I can find a copy of the OEM firmware that isn't behind HP's paywall

**Comment by plappermaul** [comment]
Please test and approve https://github.com/openwrt/openwrt/pull/18671

**Comment by jwh** [comment]
Will do with clean tree, as a side note:

   Realtek PHYs (REALTEK_PHY) [Y/n/m/?] y
    HWMON support for Realtek PHYs (REALTEK_PHY_HWMON) [N/y/?] (NEW) make[8]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1

I think this was introduced by the recent hwmon work, I resolved this in my tree by just adding the symbol to config-6.6, even though it appears it should be enabled anyway by:

define KernelPackage/phy-realtek
   SUBMENU:=$(NETWORK_DEVICES_MENU)
   TITLE:=Realtek Ethernet PHY driver
   KCONFIG:=CONFIG_REALTEK_PHY \
    CONFIG_REALTEK_PHY_HWMON=y
   DEPENDS:=+kmod-libphy +kmod-hwmon-core
   FILES:=$(LINUX_DIR)/drivers/net/phy/realtek/realtek.ko
   AUTOLOAD:=$(call AutoLoad,18,realtek,1)
endef

but it doesn't seem to actually work

**Comment by plappermaul** [comment]
@janh Can you run a show tech-support in OEM firmware on your HPE 1920-48G? 

The above patch will open up initial RTL8214FC detection and I assume that SFP GPIOs are set wrong in the DTS.

**Comment by jwh** [comment]
Yup, fair.  I'll wait for either @janh or my other switches to arrive, but I don't think it will be until next week now

**Comment by janh** [comment]
I did a quick test on my HPE 1920-48G with a current OpenWrt snapshot image.

The RTL8214FC is detected as generic PHY:
```
[   10.203258] rtl83xx-switch switch@1b000000 lan50 (uninitialized): PHY [mdio-bus:30] driver [Generic PHY] (irq=POLL)
[   10.245176] rtl83xx-switch switch@1b000000 lan52 (uninitialized): PHY [mdio-bus:31] driver [Generic PHY] (irq=POLL)
[   10.287103] rtl83xx-switch switch@1b000000 lan49 (uninitialized): PHY [mdio-bus:32] driver [Generic PHY] (irq=POLL)
[   10.329324] rtl83xx-switch switch@1b000000 lan51 (uninitialized): PHY [mdio-bus:33] driver [Generic PHY] (irq=POLL)
```

An SFP module in port 49 or 50 is detected (but the reported link speed is wrong, and traffic doesn't actually pass through):
```
[  549.893766] sfp sfp-p49: module OEM              SFP+XG-T-G       rev A    sn HTBG000001       dc 241009  
[  549.944491] hwmon hwmon0: temp1_input not attached to any thermal zone
[  554.706332] rtl83xx-switch switch@1b000000 lan49: Link is Up - 100Mbps/Full - flow control off
[  554.708168] switch: port 49(lan49) entered blocking state
[  554.752979] switch: port 49(lan49) entered forwarding state
```

Reading EEPROM data via ethtool does not work (I think that is caused by the missing PHY driver):
```
root@OpenWrt:~# ethtool -m lan49
Cannot get module EEPROM information: Not supported
```

On ports 51 and 52, the SFP module is not detected (which is expected because of the shared I2C clock), and the link is also detected (but does not work like the other ports):
```
[  646.706478] rtl83xx-switch switch@1b000000 lan51: Link is Up - 100Mbps/Full - flow control off
[  646.708181] switch: port 51(lan51) entered blocking state
[  646.753135] switch: port 51(lan51) entered forwarding state
```

> Can you run a show tech-support in OEM firmware on your HPE 1920-48G?

@plappermaul I don't think there is a way to do that on the HPE 1920 switches. It is possible to access the Realtek diag command line, though: https://github.com/janh/hpe-1910-1920-documentation/blob/master/vendor-cmdline.txt

> Yeah, I remember that - will need to wait until the other 48Gs arrive unless I can find a copy of the OEM firmware that isn't behind HP's paywall

@jwh By searching for the filename I found some Russian site which has the firmware files: https://wiki.soloshin.su/internet/online_services/hpe_and_aruba_support/firmwares_download

Not sure if you want to trust that source, but here are the sha256sums of the files which I downloaded from the HP website when it was still available:
```
53eef109243d93bfed29f9cd02d1a5610fec733c1658506e73bf0256b4e0f90b  1620-24G-JG913A_5.20.R1117.zip
2f99c087a3c053bc409c30602e79549546a3c78359df1427cc19a747ecb69732  1620-48G-JG914A_5.20.R1117.zip
ea5879f627bf03d025dd45877b227b2db76ed62979e346b3e76509f6041a5ea1  1620-8G-JG912A_5.20.R1117.zip
ce0219455eeccb16096111d698f4b3eb4ec9df1a6135366d642933d769c24ef5  1920-16G-JG923A_5.20.R1121.zip
2a6e11161d2b951c82a8e9d0d633cfa1f2f1254e13d3c719eb2f00336c1b60df  1920-24G-JG924A_5.20.R1121.zip
28bb5fb21cd6bf0efb582180d6033ee653f605d861fbb283ab53bcdb06957b23  1920-24G-PoE-180W-JG925A_5.20.R1119.zip
72979cebf56fd00a7cfbbe86747fc30752a938890069b4accc17156b9039bca2  1920-24G-PoE-370W-JG926A_5.20.R1120.zip
ccf71726fbc2f65de8035d599d29b42a1f4f6e0c12bb9fe2358c9c68e4b6c69b  1920-48G-JG927A_5.20.R1121.zip
2d74acd338cff9e64c39139f5675dbdc7adfac0f50c319f38f575e8c2c3925f8  1920-48G-PoE-370W-JG928A_5.20.R1121.zip
39b25da0eb80e1de970df6278e112258368edfa218eac793917fbff9ccd54fae  1920-8G-JG920A_5.20.R1121.zip
5d655c3721189ab7a5a5688e21d421776d21a764a53292dee96ff31ad55fd6b9  1920-8G-PoE-180W-JG922A_5.20.R1120.zip
c493206829f9cd60d85c7e9c4aa678379ff1e95e4ea6cb3de720ad8a8903f568  1920-8G-PoE-65W-JG921A_5.20.R1121.zip
```

At least for the JG927A firmware, it seems to match with the file from that site. Didn't try the others.

**Comment by jwh** [comment]
@janh awesome thanks, so I had noted it down wrong then, poe is not the same as non-poe, I'll see if I can get oem firmware loaded on this and get gpio dumps

**Comment by jwh** [comment]
@janh do you happen to know if there is a similar output like the d-links that will show gpios etc?

**Comment by janh** [comment]
@jwh I don't know any way to easily get that data. But using the diag console, you should be able to read the GPIO state (direction and value).

Based on my notes for the JG927A, the I2C SDA/SCL GPIOs are outputs in vendor firmware, and the other SFP GPIOs (mod-def0 and los) are inputs. The last two should be easy to identify with an actual SFP module (just plug in a module for mod-def0, enable/disable port on other end for los).

**Comment by jwh** [comment]
aha ok cool, got it, will figure out what they're supposed to be

is there a driver floating around that supports shared clocks or are the other 2 ports a total no go?

thanks!

**Comment by jwh** [comment]
I think I've identified the both inputs for port 49, the clocks are another matter, unfortunately debug doesn't give me any indication of what they might be :(

**Comment by stintel** [comment]
I've been using SFPs on my 2 Edgecore ECS4100-12PH switches for about a year now. As I commented on #18671, I had a [similar change](https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=commitdiff;h=ffe03a10c1adcd1c570587a97c910e761cfbffa0) to make the RTL8214FC work on RTL839x.

I do still need the change in rtl839x_read_sds_phy to have working traffic:

```diff
--- a/target/linux/realtek/files-6.6/drivers/net/phy/rtl83xx-phy.c
+++ b/target/linux/realtek/files-6.6/drivers/net/phy/rtl83xx-phy.c
@@ -310,6 +310,13 @@ int rtl839x_read_sds_phy(int phy_addr, int phy_reg)
        int reg;
        u32 val;

+       /* not sure about this one, but without it we get a "ghost" internal SERDES on addr 63 which causes breakage
+        * [    3.076655] rtl8393_serdes_probe: id: 63
+        * [    3.081135] Realtek RTL8393 SERDES rtl838x slave mii-0:3f: Detected internal RTL8390 SERDES
+        */
+       if (phy_addr > RTL839X_CPU_PORT)
+               return -EIO;
+
        if (phy_addr == 49)
                offset = 0x100;
```

**Comment by jwh** [comment]
I just applied that while I'm trying to figure out SDA/SCL, but now I get no serdes detections, 48 and 49 are also missing, is that right?

**Comment by stintel** [comment]
With that change I don't see any SERDES in dmesg. Without that change, I see this:

```
[    3.076655] rtl8393_serdes_probe: id: 63
[    3.081135] Realtek RTL8393 SERDES rtl838x slave mii-0:3f: Detected internal RTL8390 SERDES
```

But then TX doesn't seem to work on the SFP ports; RX does. Like I wrote in the comment I'm not sure about that change, and as it appears to result in some of your interfaces going missing, it's probably not correct.

**Comment by plappermaul** [comment]
Thanks for merging.

I have an idea where the ghost read comes from. Will check that before we proceed with the PHY/SERDES initialization fixup stuff.

**Comment by plappermaul** [comment]
@stintel ghost SERDES is fixed with latest version of PR https://github.com/openwrt/openwrt/pull/18402

**Comment by stintel** [comment]
> @stintel ghost SERDES is fixed with latest version of PR https://github.com/openwrt/openwrt/pull/18402

I'll try to test on Sunday.

**Comment by janh** [comment]
@jwh This command doesn't exist in the diag console on my JG927A:
```
RTK.0> ext-gpio dump dev 0
         ^Parse error
RTK.0> 
exit             - exit diag shell
chip             - chip configure
debug            - debug configuration
eee              - EEE configuration
eeep             - EEEP configuration
flowctrl         - flowctrl configuration
l2-table         - l2 table configuration
l3               - l3 configuration
led              - LED configuration
mib              - mib configuration
mirror           - mirror configuration
rspan            - RSPAN configuration
sflow            - sFlow configuration
nic              - NIC configuration
oam              - OAM configuration
port             - port configuration
qos              - QoS configuration
bandwidth        - bandwidth configuration
storm-control    - storm-control configuration
register         - register configuration
vlan             - VLAN configuration
security         - security configuration
stp              - stp configuration
switch           - switch configuration
time             - time configuration
trap             - trap configuration
trunk            - trunk configuration
acl              - ACL configuration
field-selector   - field selector configuration
range-check      - range check configuration
mpls             - MPLS configuration
diag             - diag configuration
gpio             - internal GPIO configuration
smi              - SMI configuration
```

**Comment by jwh** [comment]
Curious, so on mine I have (on r1121):

```
<HPE>_cmdline-mode on
All commands can be displayed and executed. Continue? [Y/N]Y
Please input password:**********************
Warning: Now you enter an all-command mode for developer's testing, some commands may affect operation by wrong use, please carefully use it with our engineer's direction.
<HPE>system-view
System View: return to User View with Ctrl+Z.
[HPE]_hidecmd
Now you enter a hidden command view for developer's testing, some commands may
affect operation by wrong use, please carefully use it with our engineer's
direction.
[HPE-hidecmd]debug diag
rtk sdk diag enter!
RTK.0> ext-gpio dump dev 0
    Device Status: Ready
    Device State: Enabled

    ==================================
     GPIO# | Sel. | Direction | Value
    ==================================
       00  | GPIO |    0IN    |  1
       01  | GPIO |    0IN    |  0
       02  | GPIO |    0IN    |  0
       03  | GPIO |    0IN    |  0
       04  | GPIO |    0IN    |  0
       05  | GPIO |    OUT    |  1
       06  | GPIO |    0IN    |  1
       07  | GPIO |    0IN    |  0
       08  | GPIO |    OUT    |  1
       09  | GPIO |    0IN    |  0
       10  | GPIO |    0IN    |  0
       11  | GPIO |    0IN    |  0
       12  | GPIO |    0IN    |  0
       13  | GPIO |    OUT    |  1
       14  | GPIO |    OUT    |  1
       15  | GPIO |    0IN    |  0
       16  | GPIO |    0IN    |  0
       17  | GPIO |    0IN    |  0
       18  | GPIO |    0IN    |  0
       19  | GPIO |    0IN    |  0
       20  | GPIO |    0IN    |  1
       21  | GPIO |    0IN    |  0
       22  | GPIO |    0IN    |  0
       23  | GPIO |    OUT    |  1
       24  | GPIO |    OUT    |  1
       25  | GPIO |    0IN    |  1
       26  | GPIO |    0IN    |  1
       27  | GPIO |    OUT    |  1
       28  | GPIO |    OUT    |  1
       29  | GPIO |    0IN    |  1
       30  | GPIO |    0IN    |  1
       31  | GPIO |    OUT    |  1
       32  | GPIO |    OUT    |  1
       33  | GPIO |    0IN    |  1
       34  | GPIO |    0IN    |  1
       35  | GPIO |    0IN    |  0
       36  | GPIO |    OUT    |  0
       38  | GPIO |    OUT    |  0
       39  | GPIO |    OUT    |  0
       40  | GPIO |    OUT    |  0
       48  | GPIO |    OUT    |  0
       49  | GPIO |    OUT    |  1
       50  | GPIO |    OUT    |  1
       51  | GPIO |    OUT    |  1
       52  | GPIO |    OUT    |  1
       54  | GPIO |    OUT    |  0
       55  | GPIO |    OUT    |  0

```

Is there some similar command?

**Comment by jwh** [comment]
FYI:

49: default 1, 21 def0, 22 los 
50: default 1, 25 def0, 26 los

I still can't get the clocks right

**Comment by janh** [comment]
The JG927A seems to only use the internal GPIOs, which would explain why it doesn't have that command.

Here are my notes for the JG927A:

<details>
<summary>Annotated GPIO info from `/sys/kernel/debug/gpio`</summary>

```
 gpio-488 (                    |watchdog            ) out hi 	0	watchdog
 gpio-489 (                    |sysfs               ) out lo 	1	p50/p52 scl	-> out
 gpio-490 (                    |sysfs               ) in  hi 	2	p50 sda		-> out
 gpio-491 (                    |sysfs               ) in  lo 	3	board-id-0
 gpio-492 (                    |sysfs               ) in  hi 	4	board-id-1
 gpio-493 (                    |sysfs               ) in  lo 	5	-
 gpio-494 (                    |sysfs               ) in  lo 	6	board-id-2
 gpio-495 (                    |sysfs               ) in  lo 	7	board-id-3
 gpio-496 (                    |sysfs               ) in  lo 	8	board-id-4
 gpio-497 (                    |green:power         ) out hi 	9	power-led
 gpio-498 (                    |sysfs               ) in  lo 	10	-
 gpio-499 (                    |sysfs               ) in  lo 	11	-
 gpio-500 (                    |sysfs               ) in  hi 	12	p50 mod-def0
 gpio-501 (                    |sysfs               ) in  hi 	13	p50 los
 gpio-502 (                    |sysfs               ) in  hi 	14	p52 sda		-> out
 gpio-503 (                    |sysfs               ) in  hi 	15	p52 mod-def0
 gpio-504 (                    |sysfs               ) in  hi 	16	p52 los
 gpio-505 (                    |sysfs               ) in  hi 	17	p49/p51 scl	-> out
 gpio-506 (                    |sysfs               ) in  hi 	18	p49 sda		-> out
 gpio-507 (                    |sysfs               ) in  hi 	19	p49 mod-def0
 gpio-508 (                    |sysfs               ) in  hi 	20	p49 los
 gpio-509 (                    |sysfs               ) in  hi 	21	p51 sda		-> out
 gpio-510 (                    |sysfs               ) in  hi 	22	p51 mod-def0
 gpio-511 (                    |sysfs               ) in  hi 	23	p51 los
```

</details>

<details>
<summary>GPIO directions on stock firmware</summary>

```
out
out
out
in
in
in
in
in
in
out
in
in
in
in
out
in
in
out
out
in
in
out
in
in
```

</details>

I don't remember how exactly I got the information from stock firmware. But the internal GPIOs are configured using registers 0xb8003508 (direction) and 0xb800350c (data).

The registers can be read like this:
```
[HPE-hidecmd]display memory-dump b8003508 8
B8003508:  07 42 26 00 16 F2 FF 00                          .B&.....
```

Order of the GPIOs (this example shows the direction register):
```
0000 0111 0100 0010 0010 0110 0000 0000
^       ^ ^       ^ ^       ^
|       | |       | |       |
7       0 15      8 23     16
```

**Comment by jwh** [comment]
Thanks! I guess they moved some stuff to external gpio, which isn't defined in the DTS as far as I can see, I'm not sure how I can reference it

**Comment by jwh** [comment]
So detection is working and eeprom readout is fine, no link and media type looks like its wrong, but maybe I've mixed up the gpios for los:

```
[  172.519456] rtl8214fc_media_set: port 50, set_fibre: 0
[  172.538947] rtl8214fc_power_set: Powering off FIBRE (port 50)
[  172.560438] rtl8214fc_power_set: Powering on COPPER (port 50)
[  172.581687] sfp sfp-p49: module removed
[  175.468537] sfp sfp-p49: module TP-Link          SM311LS(UN)      rev 5.0  sn 223C6H6000850    dc 240121
[  175.500737] rtl8214fc_media_set: port 50, set_fibre: 1
[  175.665804] rtl8214fc_power_set: Powering off COPPER (port 50)
[  175.687775] rtl8214fc_power_set: Powering on FIBRE (port 50)
```

```
Settings for lan49:
        Supported ports: [ TP    MII     FIBRE ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Half 1000baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Half 1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: Unknown!
        Duplex: Unknown! (255)
        Auto-negotiation: on
        master-slave cfg: preferred slave
        master-slave status: unknown
        Port: Twisted Pair
        PHYAD: 32
        Transceiver: external
        MDI-X: Unknown
        Supports Wake-on: d
        Wake-on: d
        Link detected: no
```

**Comment by plappermaul** [comment]
Good to see. Just for comparison/documentation. A functional fiber connected RTL8214FC gives on RTL838x:

```
Settings for lan25:
        Supported ports: [ TP MII FIBRE ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Half 1000baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Half 1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half
                                             100baseT/Half 100baseT/Full
        Link partner advertised pause frame use: No
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Half
        Port: Twisted Pair
        PHYAD: 24
        Transceiver: external
        Auto-negotiation: on
        MDI-X: Unknown
        Supports Wake-on: d
        Wake-on: d
        Link detected: yes
```

**Comment by jwh** [comment]
Yeah, I'm not sure why it doesn't bring it up, since it *should* have working los, any ideas?

**Comment by jwh** [comment]
Ok, so now both 49 and 50 work and pass traffic, speed and media is reported wrong (100M copper), but otherwise works

The remaining 2 I haven't found the sda/scl for, if they're shared on this also then they're not going to work of course

**Comment by plappermaul** [comment]
Nice. Just to be sure. You are talking about the HP with the RTL821FC?

**Comment by jwh** [comment]
Yup

**Comment by jwh** [comment]
I'll open a PR shortly, just want to see if I can find the right gpios for the other two first

**Comment by jwh** [comment]
https://github.com/openwrt/openwrt/pull/18696

**Comment by plappermaul** [comment]
Please close issue if it no longer exists.

**Comment by jwh** [comment]
HP 1920 works very nicely now, thank you! GS1900-48 looks to be unchanged though, do you know if it also has a RTL8214FC? With all the other work we should be pretty close I would think?

```
[    1.594961] rtl8393_serdes_probe: id: 48
[    1.599364] Realtek RTL8393 SERDES rtldsa_mdio-0:30: Detected internal RTL8390 SERDES
[    1.609951] rtl8393_serdes_probe: id: 49
[    1.614576] Realtek RTL8393 SERDES rtldsa_mdio-0:31: Detected internal RTL8390 SERDES
[    1.634634] In rtl83xx_vlan_setup
[    1.638368] UNKNOWN_MC_PMASK: 001fffffffffffff
[    1.764547] sfp sfp-p10: module TP-Link          SM311LS(UN)      rev 5.0  sn 223C6H6000850    dc 240121
[    1.932795] hwmon hwmon1: temp1_input not attached to any thermal zone
[    2.743875] rtl83xx_enable_phy_polling:    3ffffffffffff
[    3.784301] rtl83xx-switch switch@1b000000: configuring for fixed/internal link mode
[    3.793400] rtl83xx-switch switch@1b000000: Link is Up - 1Gbps/Full - flow control off
[    3.794663] rtl83xx-switch switch@1b000000 lan01 (uninitialized): PHY [mdio-bus:00] driver [REALTEK RTL8218D] (irq=POLL)
[    3.818271] rtl83xx-switch switch@1b000000 lan02 (uninitialized): PHY [mdio-bus:01] driver [REALTEK RTL8218D] (irq=POLL)
[    3.834580] rtl83xx-switch switch@1b000000 lan03 (uninitialized): PHY [mdio-bus:02] driver [REALTEK RTL8218D] (irq=POLL)
[    3.850623] rtl83xx-switch switch@1b000000 lan04 (uninitialized): PHY [mdio-bus:03] driver [REALTEK RTL8218D] (irq=POLL)
[    3.866779] rtl83xx-switch switch@1b000000 lan05 (uninitialized): PHY [mdio-bus:04] driver [REALTEK RTL8218D] (irq=POLL)
[    3.882800] rtl83xx-switch switch@1b000000 lan06 (uninitialized): PHY [mdio-bus:05] driver [REALTEK RTL8218D] (irq=POLL)
[    3.898849] rtl83xx-switch switch@1b000000 lan07 (uninitialized): PHY [mdio-bus:06] driver [REALTEK RTL8218D] (irq=POLL)
[    3.915147] rtl83xx-switch switch@1b000000 lan08 (uninitialized): PHY [mdio-bus:07] driver [REALTEK RTL8218D] (irq=POLL)
[    3.931238] rtl83xx-switch switch@1b000000 lan09 (uninitialized): PHY [mdio-bus:08] driver [REALTEK RTL8218D] (irq=POLL)
[    3.947499] rtl83xx-switch switch@1b000000 lan10 (uninitialized): PHY [mdio-bus:09] driver [REALTEK RTL8218D] (irq=POLL)
[    3.963320] rtl83xx-switch switch@1b000000 lan11 (uninitialized): PHY [mdio-bus:0a] driver [REALTEK RTL8218D] (irq=POLL)
[    3.979670] rtl83xx-switch switch@1b000000 lan12 (uninitialized): PHY [mdio-bus:0b] driver [REALTEK RTL8218D] (irq=POLL)
[    3.994984] rtl83xx-switch switch@1b000000 lan13 (uninitialized): PHY [mdio-bus:0c] driver [REALTEK RTL8218D] (irq=POLL)
[    4.011043] rtl83xx-switch switch@1b000000 lan14 (uninitialized): PHY [mdio-bus:0d] driver [REALTEK RTL8218D] (irq=POLL)
[    4.027441] rtl83xx-switch switch@1b000000 lan15 (uninitialized): PHY [mdio-bus:0e] driver [REALTEK RTL8218D] (irq=POLL)
[    4.043378] rtl83xx-switch switch@1b000000 lan16 (uninitialized): PHY [mdio-bus:0f] driver [REALTEK RTL8218D] (irq=POLL)
[    4.059363] rtl83xx-switch switch@1b000000 lan17 (uninitialized): PHY [mdio-bus:10] driver [REALTEK RTL8218D] (irq=POLL)
[    4.075532] rtl83xx-switch switch@1b000000 lan18 (uninitialized): PHY [mdio-bus:11] driver [REALTEK RTL8218D] (irq=POLL)
[    4.091416] rtl83xx-switch switch@1b000000 lan19 (uninitialized): PHY [mdio-bus:12] driver [REALTEK RTL8218D] (irq=POLL)
[    4.107684] rtl83xx-switch switch@1b000000 lan20 (uninitialized): PHY [mdio-bus:13] driver [REALTEK RTL8218D] (irq=POLL)
[    4.123776] rtl83xx-switch switch@1b000000 lan21 (uninitialized): PHY [mdio-bus:14] driver [REALTEK RTL8218D] (irq=POLL)
[    4.139647] rtl83xx-switch switch@1b000000 lan22 (uninitialized): PHY [mdio-bus:15] driver [REALTEK RTL8218D] (irq=POLL)
[    4.155850] rtl83xx-switch switch@1b000000 lan23 (uninitialized): PHY [mdio-bus:16] driver [REALTEK RTL8218D] (irq=POLL)
[    4.172133] rtl83xx-switch switch@1b000000 lan24 (uninitialized): PHY [mdio-bus:17] driver [REALTEK RTL8218D] (irq=POLL)
[    4.187801] rtl83xx-switch switch@1b000000 lan25 (uninitialized): PHY [mdio-bus:18] driver [REALTEK RTL8218D] (irq=POLL)
[    4.203691] rtl83xx-switch switch@1b000000 lan26 (uninitialized): PHY [mdio-bus:19] driver [REALTEK RTL8218D] (irq=POLL)
[    4.219731] rtl83xx-switch switch@1b000000 lan27 (uninitialized): PHY [mdio-bus:1a] driver [REALTEK RTL8218D] (irq=POLL)
[    4.234992] rtl83xx-switch switch@1b000000 lan28 (uninitialized): PHY [mdio-bus:1b] driver [REALTEK RTL8218D] (irq=POLL)
[    4.251054] rtl83xx-switch switch@1b000000 lan29 (uninitialized): PHY [mdio-bus:1c] driver [REALTEK RTL8218D] (irq=POLL)
[    4.267221] rtl83xx-switch switch@1b000000 lan30 (uninitialized): PHY [mdio-bus:1d] driver [REALTEK RTL8218D] (irq=POLL)
[    4.283319] rtl83xx-switch switch@1b000000 lan31 (uninitialized): PHY [mdio-bus:1e] driver [REALTEK RTL8218D] (irq=POLL)
[    4.299446] rtl83xx-switch switch@1b000000 lan32 (uninitialized): PHY [mdio-bus:1f] driver [REALTEK RTL8218D] (irq=POLL)
[    4.315800] rtl83xx-switch switch@1b000000 lan33 (uninitialized): PHY [mdio-bus:20] driver [REALTEK RTL8218D] (irq=POLL)
[    4.332024] rtl83xx-switch switch@1b000000 lan34 (uninitialized): PHY [mdio-bus:21] driver [REALTEK RTL8218D] (irq=POLL)
[    4.348240] rtl83xx-switch switch@1b000000 lan35 (uninitialized): PHY [mdio-bus:22] driver [REALTEK RTL8218D] (irq=POLL)
[    4.364318] rtl83xx-switch switch@1b000000 lan36 (uninitialized): PHY [mdio-bus:23] driver [REALTEK RTL8218D] (irq=POLL)
[    4.380458] rtl83xx-switch switch@1b000000 lan37 (uninitialized): PHY [mdio-bus:24] driver [REALTEK RTL8218D] (irq=POLL)
[    4.396836] rtl83xx-switch switch@1b000000 lan38 (uninitialized): PHY [mdio-bus:25] driver [REALTEK RTL8218D] (irq=POLL)
[    4.413063] rtl83xx-switch switch@1b000000 lan39 (uninitialized): PHY [mdio-bus:26] driver [REALTEK RTL8218D] (irq=POLL)
[    4.429015] rtl83xx-switch switch@1b000000 lan40 (uninitialized): PHY [mdio-bus:27] driver [REALTEK RTL8218D] (irq=POLL)
[    4.445443] rtl83xx-switch switch@1b000000 lan41 (uninitialized): PHY [mdio-bus:28] driver [REALTEK RTL8218D] (irq=POLL)
[    4.461768] rtl83xx-switch switch@1b000000 lan42 (uninitialized): PHY [mdio-bus:29] driver [REALTEK RTL8218D] (irq=POLL)
[    4.477968] rtl83xx-switch switch@1b000000 lan43 (uninitialized): PHY [mdio-bus:2a] driver [REALTEK RTL8218D] (irq=POLL)
[    4.493701] rtl83xx-switch switch@1b000000 lan44 (uninitialized): PHY [mdio-bus:2b] driver [REALTEK RTL8218D] (irq=POLL)
[    4.509389] rtl83xx-switch switch@1b000000 lan45 (uninitialized): PHY [mdio-bus:2c] driver [REALTEK RTL8218D] (irq=POLL)
[    4.525397] rtl83xx-switch switch@1b000000 lan46 (uninitialized): PHY [mdio-bus:2d] driver [REALTEK RTL8218D] (irq=POLL)
[    4.540899] rtl83xx-switch switch@1b000000 lan47 (uninitialized): PHY [mdio-bus:2e] driver [REALTEK RTL8218D] (irq=POLL)
[    4.557335] rtl83xx-switch switch@1b000000 lan48 (uninitialized): PHY [mdio-bus:2f] driver [REALTEK RTL8218D] (irq=POLL)
[    4.572750] rtl83xx-switch switch@1b000000 lan50 (uninitialized): switched to inband/1000base-x link mode
[    4.589189] rtl838x-eth 1b00a300.ethernet eth0: entered promiscuous mode
```

lan49 is absent but there is no SFP inserted...

**Comment by plappermaul** [comment]
From that log it seems as if you have a direct SerDes Connection on the SFP ports. I assume DTS says "phy-is-integrated". So no RTL8214FC here.

**Comment by jwh** [comment]
looks like we have:

INTERNAL_PHY(48)

and

```
                port@48 {
                        reg = <48>;
                        label = "lan49";
                        phy-mode = "sgmii";
                        phy-handle = <&phy48>;
                        sfp = <&sfp0>;

                        fixed-link {
                                speed = <1000>;
                                full-duplex;
                                pause;
                        };

                };
```

I guess we're still missing some setup here, any ideas?

**Comment by jwh** [comment]
As pretty much everything is in now and no change for the GS1900-48, do you think you will have time to revisit this @plappermaul ?

It's not a problem now that the 1920s work ok and arguably they are a better choice over the GS1900, but it would be nice if it is feasible to get all ports working

**Comment by plappermaul** [comment]
I'm currently focused on some RTL930x patches. So this might take a while. Sorry for that.

**Comment by jwh** [comment]
No problem! I'll close this and open a new one specifically for the GS1900-48 as this one has a lot of noise

**Comment by plappermaul** [comment]
Quick check about the directly via SerDes attached SFP (not via RTL8214FC). Does it tell you speed 10MBit if NO module is inserted? Like this:

```
root@OpenWrt:~# ethtool lan10
Settings for lan10:
        Supported ports: [ MII ]
        Supported link modes:   1000baseT/Full
                                1000baseX/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  1000baseT/Full
                                1000baseX/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: 10Mb/s
        Duplex: Half
        Port: MII
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: on
        Supports Wake-on: d
        Wake-on: d
        Link detected: no
```

**Comment by jwh** [comment]
Hey, sorry haven't had chance to open a new issue, but to answer your question, no, they show 1000/full without SFPs and 10/half with 1G lx plugged in but no light:

```
root@swdev-zyxel-gs1900-48:~# ethtool lan49
Settings for lan49:
        Supported ports: [ MII ]
        Supported link modes:   1000baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  1000baseT/Full
        Link partner advertised pause frame use: Symmetric
        Link partner advertised auto-negotiation: No
        Link partner advertised FEC modes: Not reported
        Speed: 1000Mb/s
        Duplex: Full
        Auto-negotiation: on
        Port: MII
        PHYAD: 0
        Transceiver: internal
        Supports Wake-on: d
        Wake-on: d
        Link detected: no
```

**Comment by plappermaul** [comment]
if you have time to support @jonasjelonek then feel free to go on here. Otherwise please close this PR.

**Comment by jwh** [comment]
I know where both of these devices are, I can surely test. @jonasjelonek what do you need?

**Comment by plappermaul** [comment]
IIRC.

- GS1920-48G -> RTL8214FC -> works
- GS1900-48 has direct SFP connections -> so this could be made working with SFP setup.

**Comment by jonasjelonek** [comment]
> I know where both of these devices are, I can surely test. [@jonasjelonek](https://github.com/jonasjelonek) what do you need?

First of all, the current status and issue(s) here to get me in the loop. Not sure what still persists after this has been stale for quite some time. DTS of GS1900-48 looks good.

If somethings not working, we can have a look at the normal or SerDes registers. Dumps there are needed, SerDes registers via debugfs, normal registers via devmem.

**Comment by jwh** [comment]
That's right yes, 48G is all fine, I'll build from HEAD and see what's changed on the GS1900

**Comment by jwh** [comment]
Unfortunately I'm hitting an unrelated build issue with netifd, I don't have the time to debug it though, if you can see whats wrong:

```
In file included from main.c:14:
../../../staging_dir/toolchain-mips_24kc_gcc-14.3.0_musl/include/fortify/stdio.h: In function 'snprintf':
../../../staging_dir/toolchain-mips_24kc_gcc-14.3.0_musl/include/fortify/stdio.h:101:9: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  101 |         return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack());
      |         ^~~~~~
../../../staging_dir/toolchain-mips_24kc_gcc-14.3.0_musl/include/fortify/stdio.h: In function 'sprintf':
../../../staging_dir/toolchain-mips_24kc_gcc-14.3.0_musl/include/fortify/stdio.h:110:17: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  110 |                 __r = __orig_snprintf(__s, __b, __f, __builtin_va_arg_pack());
      |                 ^~~
../../../staging_dir/toolchain-mips_24kc_gcc-14.3.0_musl/include/fortify/stdio.h:114:17: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  114 |                 __r = __orig_sprintf(__s, __f, __builtin_va_arg_pack());
      |                 ^~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Comment by plappermaul** [comment]
In case you do not come from a clean environment. Had several issues due to tool updates the last weeks jumping back and forth. Try to rebuild toolchain.

make targetclean

**Comment by jwh** [comment]
Aha, that'll do it, thanks

**Comment by jwh** [comment]
Just flashed HEAD, no change - light but no link unless `rtl network on` is done before boot, I have devmem etc in my image, @jonasjelonek what do you need?

**Comment by plappermaul** [comment]
Thanks. 

According to the DTS port 49/50 are driven by serdes12 & serdes13. So focus on port 49 and serdes 12. Please post an output of /sys/kernel/debugfs/realtek_otto_serdes/serdes.12/registers. Once in the non working version and once in the working version. Each with plugged in modules. 

Btw. Please adapt topic to "realtek: SFPs on GS1900-48 ..."

**Comment by jwh** [comment]
Without `rtk network on`:

```
root@swdev-zyxel-gs1900-48:~# cat /sys/kernel/debug/realtek_otto_serdes/serdes.13/registers
Back SDS 13:   00   01   02   03   04   05   06   07   08   09   0A   0B   0C   0D   0E   0F   10   11   12   13   14   15   16   17   18   19   1A   1B   1C   1D   1E   1F
SDS        : 1403 0F00 70C0 7106 0749 8E0F 8F5F 5359 524B 0000 8FA4 0000 08EC 4636 2053 0000 0000 0000 0000 4001 0001 4001 9800 9800 001C 001C 3810 0000 C040 0000 0000 0000
SDS_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 258F 0000 0000 41F5 7A09 0C50 0000 0000 0000 0000 0015 FFFF 0002 0000 0000 0100 0000 0000
FIB        : 1940 6189 0000 0000 01A0 0000 0002 0004 0000 0000 0000 0000 0000 0000 0000 8000 0083 0000 0000 0000 0000 0000 0001 4001 0000 0000 0000 0000 33FA 646A 071E 0000
FIB_EXT    : 0140 6109 0000 0000 0020 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 2210 0000 0124 031B 1F33 0000 0000 1408 0000 0000 0000 0000 0000 0000 0000 0000
DTE        : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
DTE_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX        : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG     : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG_EXT : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_TG     : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508
ANA_TG_EXT : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 003F
root@swdev-zyxel-gs1900-48:~# cat /sys/kernel/debug/realtek_otto_serdes/serdes.12/registers
Back SDS 12:   00   01   02   03   04   05   06   07   08   09   0A   0B   0C   0D   0E   0F   10   11   12   13   14   15   16   17   18   19   1A   1B   1C   1D   1E   1F
SDS        : 1403 0F00 70C0 7106 0749 8E0F 8F5F 5359 524B 0000 8FA4 0000 08EC 4636 2053 0000 0000 0000 0000 4001 0001 4001 9800 9800 001C 001C 3810 0000 C040 0000 0000 0000
SDS_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 258F 0000 0000 41F5 7A09 0C50 0000 0000 0000 0000 0015 0000 0000 0000 0000 0100 0000 0000
FIB        : 1940 6189 0000 0000 01A0 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 0083 0000 0000 0000 0000 0000 0001 4001 0000 0000 0000 0000 33FA 646A 071E 0000
FIB_EXT    : 0140 6109 0000 0000 0020 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 2210 0000 0124 031B 1F33 0000 0000 1408 0000 0000 0000 0000 0000 0000 0000 0000
DTE        : 2040 0000 0000 0000 0001 0028 0000 0000 8000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0010 0000 0000 0000 0800 0000 0000 0000 0000 0000 0000 0000
DTE_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX        : 0007 0300 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG     : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG_EXT : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_TG     : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508
ANA_TG_EXT : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0222 C508
root@swdev-zyxel-gs1900-48:~#
```

With `rtk network on`:

```
root@swdev-zyxel-gs1900-48:~# cat /sys/kernel/debug/realtek_otto_serdes/serdes.13/registers
Back SDS 13:   00   01   02   03   04   05   06   07   08   09   0A   0B   0C   0D   0E   0F   10   11   12   13   14   15   16   17   18   19   1A   1B   1C   1D   1E   1F
SDS        : 1403 0F00 70C0 7106 0749 8E0F 8F5F 5359 524B 0000 8FA4 0000 08EC 4636 2053 0000 0000 0000 0000 4001 0001 4001 9800 9800 001C 001C 3810 0000 C040 0000 0000 0000
SDS_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 258F 0000 0000 41F5 7A09 0C50 0000 0000 0000 0000 0015 FFFF 0006 0000 0000 0111 0000 0000
FIB        : 1140 61AD 0000 0000 01A0 41A0 0002 0004 0000 0000 0000 0000 0000 0000 0000 8000 0083 0000 0000 0000 0000 0000 0001 4001 0000 0000 0000 0000 33FA 646A 071E 0000
FIB_EXT    : 0140 6109 0000 0000 0020 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 2210 0000 0124 031B 1F33 E007 0000 1408 0000 0000 0000 0000 0000 0000 0000 0000
DTE        : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
DTE_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX        : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG     : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG_EXT : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_TG     : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508
ANA_TG_EXT : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 003F
root@swdev-zyxel-gs1900-48:~# cat /sys/kernel/debug/realtek_otto_serdes/serdes.12/registers
Back SDS 12:   00   01   02   03   04   05   06   07   08   09   0A   0B   0C   0D   0E   0F   10   11   12   13   14   15   16   17   18   19   1A   1B   1C   1D   1E   1F
SDS        : 1403 0F00 70C0 7106 0749 8E0F 8F5F 5359 524B 0000 8FA4 0000 08EC 4636 2053 0000 0000 0000 0000 4001 0001 4001 9800 9800 001C 001C 3810 0000 C040 0000 0000 0000
SDS_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 258F 0000 0000 41F5 7A09 0C50 0000 0000 0000 0000 0015 0000 0000 0000 0000 0100 0000 0000
FIB        : 1140 6189 0000 0000 01A0 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 0083 0000 0000 0000 0000 0000 0001 4001 0000 0000 0000 0000 33FA 646A 071E 0000
FIB_EXT    : 0140 6109 0000 0000 0020 0000 0000 0004 0000 0000 0000 0000 0000 0000 0000 8000 2210 0000 0124 031B 1F33 6000 0000 1408 0000 0000 0000 0000 0000 0000 0000 0000
DTE        : 2040 0000 0000 0000 0001 0028 0000 0000 8000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0010 0000 0000 0000 0800 0000 0000 0000 0000 0000 0000 0000
DTE_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX        : 0007 0300 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
TGX_EXT    : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG     : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_RG_EXT : 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
ANA_TG     : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508
ANA_TG_EXT : 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0222 C508 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0222 C508
root@swdev-zyxel-gs1900-48:~#

```
SFP is actually in lan 50, posted both for comparson

**Comment by plappermaul** [comment]
Thank you. Please additionally post content of https://svanheule.net/realtek/cypress/register/mac_serdes_if_ctrl for both cases.

```
devmem 0x1b000008
devmem 0x1b00000c
```

**Comment by jwh** [comment]
```
root@swdev-zyxel-gs1900-48:~# devmem 0x1b000008
0x66666666
root@swdev-zyxel-gs1900-48:~# devmem 0x1b00000c
0x00776666
root@swdev-zyxel-gs1900-48:~#
```

**Comment by jonasjelonek** [comment]
Setting 1000Base-X/SGMII on RTL839x SerDes is there but commented since I didn't have a way to test it. You could uncomment it https://github.com/openwrt/openwrt/blob/85250b94f643c5989a333e08304244fbc98484ac/target/linux/realtek/files-6.12/drivers/net/pcs/pcs-rtl-otto.c#L865C12-L865C35

Maybe it just works or it requires some more pre-init for that.

**Comment by plappermaul** [comment]
Just to be sure. The devmem is the same for both cases?

**Comment by jwh** [comment]
Sorry, yes

**Comment by plappermaul** [comment]
Then some more register init is needed.

**Comment by jwh** [comment]
> Setting 1000Base-X/SGMII on RTL839x SerDes is there but commented since I didn't have a way to test it. You could uncomment it https://github.com/openwrt/openwrt/blob/85250b94f643c5989a333e08304244fbc98484ac/target/linux/realtek/files-6.12/drivers/net/pcs/pcs-rtl-otto.c#L865C12-L865C35
> 
> Maybe it just works or it requires some more pre-init for that.

No change unfortunately

**Comment by plappermaul** [comment]
We are currently only doing the basic 10G setup for serdes 8/9/12/13. I assume this is missing from SDK. 

```
    if (HWP_SDS_MODE(unit, 12) == RTK_MII_1000BX_FIBER)
    {
        Serdes_set(unit, 0xb880,  11  , 11  , 0x1);
        ret = phy_speed_set(unit, 48, PORT_SPEED_1000M);
        if (ret != RT_ERR_OK)
        {
            RT_ERR(ret, (MOD_DAL|MOD_GENERAL), "");
        }
    }

    if (HWP_SDS_MODE(unit, 13) == RTK_MII_1000BX_FIBER)
    {
        Serdes_set(unit, 0xb980,  11  , 11  , 0x1);
        ret = phy_speed_set(unit, 49, PORT_SPEED_1000M);
        if (ret != RT_ERR_OK)
        {
            RT_ERR(ret, (MOD_DAL|MOD_GENERAL), "");
        }
    }

```

And going deeper the phy_speed_set (aka phy_8390_speed_set) we get into _phy_8390_init_fiber_1g_s12 and _phy_8390_init_fiber_1g_s13.

```
void _phy_8390_init_fiber_1g_s12(uint32 unit)
{
    PHY_8390_SERDES_SET(0xb818,  3 , 3  , 0x0);
    PHY_8390_SERDES_SET(0xbbfc,  16 , 16  , 0x1);
    PHY_8390_SERDES_SET(0xbbfc,  19 , 18  , 0x2);
    PHY_8390_SERDES_SET(0xbb58,  0 , 0  , 0x1);
    PHY_8390_SERDES_SET(0xbb58,  4 , 4  , 0x1);
    PHY_8390_SERDES_SET(0xbb58,  16 , 16  , 0x1);
    PHY_8390_SERDES_SET(0xbb58,  20 , 20  , 0x1);

    PHY_8390_SERDES_SET(0xbb38,  15 , 0  , 0x0722);
    PHY_8390_SERDES_SET(0xbb40,  15 , 0  , 0x18f5);
    PHY_8390_SERDES_SET(0xbb00,  11 , 11  , 0x0);
    PHY_8390_SERDES_SET(0xb804,  9 , 8  , 0x0);
    PHY_8390_SERDES_SET(0xb880,  13 , 13  , 0x0);
    PHY_8390_SERDES_SET(0xb880,  6 , 6  , 0x1);
    PHY_8390_SERDES_SET(0xb880,  12 , 12  , 0x1);

    PHY_8390_SERDES_SET(0xbb20,  5 , 5  , 0x1);
    PHY_8390_SERDES_SET(0xbb1c,  11 , 7  , 0x15);

    PHY_8390_SERDES_SET(0xbbf8,  21 , 20  , 0x3);
    PHY_8390_SERDES_SET(0xbb20,  3  , 3  , 0x0);
    PHY_8390_SERDES_SET(0xbb40,  15  , 15  , 0x1);
    osal_time_usleep(100 * 1000);
    PHY_8390_SERDES_SET(0xbb40,  15  , 15  , 0x0);
    PHY_8390_SERDES_SET(0xbbf8,  21 , 20  , 0x1);
    PHY_8390_SERDES_SET(0xbbf8,  21 , 20  , 0x0);
}

void _phy_8390_init_fiber_1g_s13(uint32 unit)
{
    PHY_8390_SERDES_SET(0xb918,  3 , 3  , 0x0);
    PHY_8390_SERDES_SET(0xbbfc,  17 , 17  , 0x1);
    PHY_8390_SERDES_SET(0xbbfc,  21 , 20  , 0x2);
    PHY_8390_SERDES_SET(0xbbd8,  0 , 0  , 0x1);
    PHY_8390_SERDES_SET(0xbbd8,  4 , 4  , 0x1);
    PHY_8390_SERDES_SET(0xbbd8,  16 , 16  , 0x1);
    PHY_8390_SERDES_SET(0xbbd8,  20 , 20  , 0x1);

    PHY_8390_SERDES_SET(0xbbb8,  15 , 0  , 0x0722);
    PHY_8390_SERDES_SET(0xbbc0,  15 , 0  , 0x18f5);
    PHY_8390_SERDES_SET(0xbb80,  11 , 11  , 0x0);
    PHY_8390_SERDES_SET(0xb904,  9 , 8  , 0x0);
    PHY_8390_SERDES_SET(0xb980,  13 , 13  , 0x0);
    PHY_8390_SERDES_SET(0xb980,  6 , 6  , 0x1);
    PHY_8390_SERDES_SET(0xb980,  12 , 12  , 0x1);

    PHY_8390_SERDES_SET(0xbba0,  5 , 5  , 0x1);
    PHY_8390_SERDES_SET(0xbb9c,  11 , 7  , 0x15);

    PHY_8390_SERDES_SET(0xbbf8,  23 , 22  , 0x0003);
    PHY_8390_SERDES_SET(0xbba0,  3  , 3  , 0x0);
    PHY_8390_SERDES_SET(0xbbc0,  15  , 15  , 0x1);

    osal_time_usleep(100 * 1000);

    PHY_8390_SERDES_SET(0xbbc0,  15  , 15  , 0x0);
    PHY_8390_SERDES_SET(0xbbf8,  23 , 22  , 0x0001);
    PHY_8390_SERDES_SET(0xbbf8,  23 , 22  , 0x0000);
}

```

**Comment by plappermaul** [comment]
Thanks for the time testing this.

**Comment by jwh** [comment]
No worries - just hoping to help get it fixed, I'll probably get rid of it soon if someone wants it (and probably the 48G poe 370w)
